"""
Robustness Warning Flags — Prompt 07.

Implements automated diagnostic flags for common research integrity risks.

IMPORTANT:
    These are WARNINGS, not verdicts.
    They identify patterns that deserve scrutiny.
    They are NOT proof of overfitting.
    They are NOT grounds for automatic strategy disqualification.
    They should be disclosed in all research reports.

Warning codes (from Prompt 07 spec):
    LOW_SAMPLE_WARNING          — fewer trades than configured minimum
    LOW_OOS_SAMPLE              — fewer OOS windows than minimum
    HIGH_PARAMETER_SENSITIVITY  — performance changes >threshold across param neighborhood
    HIGH_COST_SENSITIVITY       — result materially weaker under adverse costs
    SINGLE_ASSET_DEPENDENCY     — removing one asset materially changes aggregate
    SINGLE_TIMEFRAME_DEPENDENCY — behavior concentrated in one timeframe
    SINGLE_PERIOD_DEPENDENCY    — most of result from one historical period
    REGIME_DEPENDENCY           — heavily concentrated in one market regime
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class WarningCode(str, Enum):
    LOW_SAMPLE_WARNING = "LOW_SAMPLE_WARNING"
    LOW_OOS_SAMPLE = "LOW_OOS_SAMPLE"
    HIGH_PARAMETER_SENSITIVITY = "HIGH_PARAMETER_SENSITIVITY"
    HIGH_COST_SENSITIVITY = "HIGH_COST_SENSITIVITY"
    SINGLE_ASSET_DEPENDENCY = "SINGLE_ASSET_DEPENDENCY"
    SINGLE_TIMEFRAME_DEPENDENCY = "SINGLE_TIMEFRAME_DEPENDENCY"
    SINGLE_PERIOD_DEPENDENCY = "SINGLE_PERIOD_DEPENDENCY"
    REGIME_DEPENDENCY = "REGIME_DEPENDENCY"


@dataclass
class ResearchWarning:
    """A single diagnostic warning generated by the robustness framework."""
    code: WarningCode
    description: str
    evidence: str           # quantitative evidence that triggered the warning
    context: str = ""       # optional extra context (e.g. which asset/strategy)
    severity: str = "WARN"  # WARN | INFO

    def to_dict(self) -> dict:
        return {
            "code": self.code.value,
            "severity": self.severity,
            "description": self.description,
            "evidence": self.evidence,
            "context": self.context,
        }


class RobustnessWarningEngine:
    """
    Evaluates research results and generates diagnostic warning flags.

    All check methods are pure functions of their inputs.
    They never modify strategy state or execution parameters.
    """

    def __init__(self, min_trades: int = 30, min_oos_windows: int = 5) -> None:
        self._min_trades = min_trades
        self._min_oos_windows = min_oos_windows

    def check_trade_count(self, trade_count: int, context: str = "") -> list[ResearchWarning]:
        """Warn if the sample is too small for reliable conclusions."""
        if trade_count < self._min_trades:
            return [ResearchWarning(
                code=WarningCode.LOW_SAMPLE_WARNING,
                description=(
                    f"Trade count ({trade_count}) is below the configured minimum "
                    f"({self._min_trades}). Conclusions from small samples are unreliable."
                ),
                evidence=f"trade_count={trade_count}, threshold={self._min_trades}",
                context=context,
            )]
        return []

    def check_oos_window_count(self, oos_window_count: int, context: str = "") -> list[ResearchWarning]:
        """Warn if the number of valid OOS windows is too small."""
        if oos_window_count < self._min_oos_windows:
            return [ResearchWarning(
                code=WarningCode.LOW_OOS_SAMPLE,
                description=(
                    f"Number of valid OOS windows ({oos_window_count}) is below the "
                    f"configured minimum ({self._min_oos_windows})."
                ),
                evidence=f"oos_windows={oos_window_count}, threshold={self._min_oos_windows}",
                context=context,
            )]
        return []

    def check_parameter_sensitivity(
        self,
        param_name: str,
        baseline_metric: float,
        variant_metrics: list[float],
        sensitivity_threshold_pct: float = 30.0,
    ) -> list[ResearchWarning]:
        """
        Warn if performance varies by more than `sensitivity_threshold_pct`
        across the tested parameter neighborhood.

        This is NOT optimization. It measures stability, not the best value.
        """
        if not variant_metrics or baseline_metric == 0:
            return []

        max_deviation = max(abs(v - baseline_metric) / abs(baseline_metric) for v in variant_metrics) * 100.0
        if max_deviation > sensitivity_threshold_pct:
            return [ResearchWarning(
                code=WarningCode.HIGH_PARAMETER_SENSITIVITY,
                description=(
                    f"Parameter '{param_name}': performance varies by up to "
                    f"{max_deviation:.1f}% across tested neighborhood "
                    f"(threshold: {sensitivity_threshold_pct}%). "
                    "This indicates sensitivity, not proof of overfitting."
                ),
                evidence=f"max_deviation={max_deviation:.2f}%, baseline={baseline_metric:.4f}",
                context=f"param={param_name}",
            )]
        return []

    def check_cost_sensitivity(
        self,
        baseline_pnl: float,
        adverse_pnl: float,
        adverse_label: str,
        degradation_threshold_pct: float = 50.0,
    ) -> list[ResearchWarning]:
        """
        Warn if P&L degrades by more than `degradation_threshold_pct`
        under adverse cost assumptions.
        """
        if baseline_pnl == 0:
            return []

        degradation = (baseline_pnl - adverse_pnl) / abs(baseline_pnl) * 100.0
        if degradation > degradation_threshold_pct:
            return [ResearchWarning(
                code=WarningCode.HIGH_COST_SENSITIVITY,
                description=(
                    f"Net P&L degrades by {degradation:.1f}% under '{adverse_label}' "
                    f"cost scenario (threshold: {degradation_threshold_pct}%). "
                    "Result may not survive realistic cost increases."
                ),
                evidence=(
                    f"baseline_pnl={baseline_pnl:.4f}, "
                    f"adverse_pnl={adverse_pnl:.4f}, "
                    f"degradation={degradation:.2f}%"
                ),
                context=adverse_label,
            )]
        return []

    def check_asset_dependency(
        self,
        asset_pnl_contributions: dict[str, float],
        total_pnl: float,
        concentration_threshold_pct: float = 70.0,
    ) -> list[ResearchWarning]:
        """
        Warn if one asset accounts for more than `concentration_threshold_pct`
        of total P&L.
        """
        if total_pnl == 0 or not asset_pnl_contributions:
            return []

        warnings = []
        for asset, pnl in asset_pnl_contributions.items():
            share = abs(pnl) / abs(total_pnl) * 100.0
            if share > concentration_threshold_pct:
                warnings.append(ResearchWarning(
                    code=WarningCode.SINGLE_ASSET_DEPENDENCY,
                    description=(
                        f"Asset '{asset}' accounts for {share:.1f}% of total P&L "
                        f"(threshold: {concentration_threshold_pct}%). "
                        "Result may not generalize beyond this asset."
                    ),
                    evidence=f"asset={asset}, share={share:.2f}%, total_pnl={total_pnl:.4f}",
                    context=asset,
                ))
        return warnings

    def check_timeframe_dependency(
        self,
        timeframe_pnl_contributions: dict[str, float],
        total_pnl: float,
        concentration_threshold_pct: float = 70.0,
    ) -> list[ResearchWarning]:
        """Warn if one timeframe accounts for most of the total P&L."""
        if total_pnl == 0 or not timeframe_pnl_contributions:
            return []

        warnings = []
        for tf, pnl in timeframe_pnl_contributions.items():
            share = abs(pnl) / abs(total_pnl) * 100.0
            if share > concentration_threshold_pct:
                warnings.append(ResearchWarning(
                    code=WarningCode.SINGLE_TIMEFRAME_DEPENDENCY,
                    description=(
                        f"Timeframe '{tf}' accounts for {share:.1f}% of total P&L "
                        f"(threshold: {concentration_threshold_pct}%)."
                    ),
                    evidence=f"timeframe={tf}, share={share:.2f}%",
                    context=tf,
                ))
        return warnings

    def check_period_dependency(
        self,
        period_pnl_contributions: dict[str, float],
        total_pnl: float,
        concentration_threshold_pct: float = 70.0,
    ) -> list[ResearchWarning]:
        """Warn if one historical period accounts for most of total P&L."""
        if total_pnl == 0 or not period_pnl_contributions:
            return []

        warnings = []
        for period, pnl in period_pnl_contributions.items():
            share = abs(pnl) / abs(total_pnl) * 100.0
            if share > concentration_threshold_pct:
                warnings.append(ResearchWarning(
                    code=WarningCode.SINGLE_PERIOD_DEPENDENCY,
                    description=(
                        f"Period '{period}' accounts for {share:.1f}% of total P&L. "
                        "Result may depend on a single market episode."
                    ),
                    evidence=f"period={period}, share={share:.2f}%",
                    context=period,
                ))
        return warnings

    def check_regime_dependency(
        self,
        regime_pnl_contributions: dict[str, float],
        total_pnl: float,
        concentration_threshold_pct: float = 70.0,
    ) -> list[ResearchWarning]:
        """Warn if one market regime accounts for most of total P&L."""
        if total_pnl == 0 or not regime_pnl_contributions:
            return []

        warnings = []
        for regime, pnl in regime_pnl_contributions.items():
            share = abs(pnl) / abs(total_pnl) * 100.0
            if share > concentration_threshold_pct:
                warnings.append(ResearchWarning(
                    code=WarningCode.REGIME_DEPENDENCY,
                    description=(
                        f"Regime '{regime}' accounts for {share:.1f}% of total P&L. "
                        "Performance may be regime-specific. Investigate further."
                    ),
                    evidence=f"regime={regime}, share={share:.2f}%",
                    context=regime,
                ))
        return warnings
